Lab 1
Understanding Basics of Machine Learning Programming using Python – Pandas & Numpy

Numpy description
Speed & Performance: Standard Python lists can be slow when processing millions of items. NumPy arrays are stored in contiguous memory locations, making access and manipulation significantly faster.Vectorized Operations: You can perform calculations across whole arrays without writing explicit for loops.  Foundation for Data Science: Essential libraries like Pandas, SciPy, and Scikit-learn are built on top of NumPy.


In [1]:
#testing it out
import numpy as np
import pandas as pd

array = np.array([1,2,3,4,5])

# Creating a 2D array (matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d.ndim)   # dimension of the array
print(arr2d.shape)  # Output: (2, 3)
print(arr2d.size)   # total elements
print(arr2d.dtype)  # type of data

# Array filled with zeros
zeros = np.zeros((2, 3))

# Array filled with ones
ones = np.ones((3, 3))

# Array with a sequence of numbers (start, stop, step)
sequence = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# Array of linearly spaced numbers (start, stop, num_elements)
linespace = np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1. ]

#reshaping array
# Array filled with zeros
zeros = np.zeros((2, 3))

# Array filled with ones
ones = np.ones((3, 3))

# Array with a sequence of numbers (start, stop, step)
sequence = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# Array of linearly spaced numbers (start, stop, num_elements)
linespace = np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1. ]


2
(2, 3)
6
int64


Q1. Create a NumPy array of integers from 1 to 20, reshape it into a 4x5 matrix, and find its transpose, sum, mean, and standard deviation.

In [2]:
array = np.arange(1,21)
array = array.reshape(4,5)

TransposeArr = array.T
total_sum = array.sum()
meanArr = array.mean()
StandardDeviationArr = np.std(array)

Q2. Write a NumPy program to create two 3x3 matrices and perform addition, subtraction, multiplication (element-wise and matrix multiplication) and find the determinant of one matrix.

In [3]:
mat1 = np.ones((3,3))
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

addMatrix = mat1+mat2
subMatrix = mat1-mat2
mulMatrix = mat1*mat2 #multiples the element only
MatrixMulti = np.matmul(mat1,mat2)
print(MatrixMulti)

determinantMat1 = np.linalg.det(mat1)
determinantMat2 = np.linalg.det(mat2)
print(np.round(determinantMat1, 2))

[[12. 15. 18.]
 [12. 15. 18.]
 [12. 15. 18.]]
0.0


Q3. Create a Pandas DataFrame from a dictionary containing student names, marks in three subjects, and display the top rows, data types, and summary statistics.

In [4]:
import pandas as pd
data ={
    "name" : ["Bhargav","Sujal","Vishwas"],
    "Subject1" : [90,85,80],
    "Subject2" : [80,90,100],
    "Subject3" : [93,94,95],
}
df = pd.DataFrame(data)
print(df.head())
print(df.dtypes)
print(df.describe())

      name  Subject1  Subject2  Subject3
0  Bhargav        90        80        93
1    Sujal        85        90        94
2  Vishwas        80       100        95
name          str
Subject1    int64
Subject2    int64
Subject3    int64
dtype: object
       Subject1  Subject2  Subject3
count       3.0       3.0       3.0
mean       85.0      90.0      94.0
std         5.0      10.0       1.0
min        80.0      80.0      93.0
25%        82.5      85.0      93.5
50%        85.0      90.0      94.0
75%        87.5      95.0      94.5
max        90.0     100.0      95.0


Exercise Questions
1.	Convert a 1-D array into a 2-D array with 3 rows.

In [5]:
array = np.array([1,2,3,4,5,6,7,8,9])
array = array.reshape(3,-1) #here -1 will auto decide the number of columns each row will get
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2.	Write a Python program to demonstrate basic operations using NumPy arrays (creation, reshaping, indexing, slicing).

In [6]:
array = np.array([1,2,3,4,5,6,7,8,9])
array = array.reshape(3,-1)
firstEle = array[0]
array = np.array([1,2,3,4,5,6,7,8,9])
#basic slicing
#sequence [ start: stop:step]
print(array[0:3])
print(array[0:8:2])
print(array[0::2])
print(array[3::2])

[1 2 3]
[1 3 5 7]
[1 3 5 7 9]
[4 6 8]


3.	Consider the following matrices :
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
Write a python program to perform the following using Numeric Python (numpy).
i)	Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
ii)	Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
iii)	Product of two matrices A and B, and print the resultant matrix D
iv)	Sort the elements of resultant matrix C and print the resultant Matrix E.
v)	Transpose the Matrix E and print the result


In [7]:
ArrayA = np.array([[1,2,3], [4,5,6],[7,8,10]])
ArrayB = np.array([[7, 8, 10], [4,5,6],[1, 2, 3]])

In [8]:
MatrixC = np.add(ArrayA,ArrayB)
print(MatrixC)
MatrixE = np.subtract(ArrayA,ArrayB)
print(MatrixE)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [9]:
sumOfArrayA = np.sum(ArrayA)
print(sumOfArrayA)
sumOfArrayB = np.sum(ArrayB,axis=0)
print(sumOfArrayB)
sumOfArrayC = np.sum(MatrixC,axis=1)
print(sumOfArrayC)

46
[12 15 19]
[31 30 31]


In [10]:
MatrixD = np.matmul(ArrayA,ArrayB)
print(MatrixD)

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


In [11]:
MatrixC.sort()
print(MatrixC)

# print(MatrixE)
MatrixE = MatrixE.transpose()
print(MatrixE)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]


4.Write a Python program to group a dataset by a categorical column and compute aggregate 
sta s cs (mean, sum, count) for each group using groupby()

In [12]:
# 1. Create a sample dataset
data = {
    "Department": ["Sales", "Engineering", "Sales", "HR", "Engineering", "Sales", "HR"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace"],
    "Salary": [70000, 110000, 80000, 65000, 120000, 75000, 62000],
    "Bonus": [5000, 10000, 6000, 4000, 12000, 5500, 4500],
}

df = pd.DataFrame(data)

# 2. Group by the categorical column 'Department' and aggregate 'Salary'
salary_stats = df.groupby("Department")["Salary"].agg(["mean", "sum", "count"])

# 3. Clean up the column names and formatting
salary_stats = salary_stats.rename(
    columns={"mean": "Average_Salary", "sum": "Total_Salary", "count": "Employee_Count"}
)

print("--- Salary Statistics by Department ---")
print(salary_stats)

--- Salary Statistics by Department ---
             Average_Salary  Total_Salary  Employee_Count
Department                                               
Engineering        115000.0        230000               2
HR                  63500.0        127000               2
Sales               75000.0        225000               3


5.  Write a Python program to pivot a dataset into a cross-tabulated summary table using 
pivot_table(), with a specified aggrega on func on.

In [13]:
import pandas as pd

# 1. Create a sample sales dataset
data = {
    "Region": ["East", "West", "East", "North", "West", "North", "East", "West"],
    "Product": ["Laptop", "Laptop", "Desktop", "Tablet", "Tablet", "Laptop", "Tablet", "Desktop"],
    "Sales": [1200, 1500, 800, 400, 450, 1300, 500, 850],
}

df = pd.DataFrame(data)

# 2. Pivot the dataset: Region as rows, Product as columns, aggregate Sales with sum
pivot_summary = df.pivot_table(
    index="Region",          # Rows
    columns="Product",       # Columns
    values="Sales",          # Values to aggregate
    aggfunc="sum",           # Aggregation function (e.g., 'sum', 'mean', 'count')
    fill_value=0,            # Replace NaN where combinations don't exist
    margins=True,            # Add row/column totals
    margins_name="Total"     # Label for total rows/columns
)

print(pivot_summary)

Product  Desktop  Laptop  Tablet  Total
Region                                 
East         800    1200     500   2500
North          0    1300     400   1700
West         850    1500     450   2800
Total       1650    4000    1350   7000


6. Write a Python program to apply a custom func on row-wise/column-wise on a DataFrame 
using apply() and lambda expressions (e.g., crea ng a new derived feature).

In [14]:
import pandas as pd

# 1. Create a sample dataset of student test scores
data = {
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 45, 92, 60],
    "Science": [90, 55, 88, 70],
    "English": [78, 62, 95, 65],
}

df = pd.DataFrame(data)

# 2. Row-wise apply (axis=1): Derive total score and calculate final grade
# Axis=1 passes each row as a Pandas Series to the lambda function
df["Total_Score"] = df.apply(lambda row: row["Math"] + row["Science"] + row["English"], axis=1)

df["Status"] = df.apply(
    lambda row: "Pass" if (row["Total_Score"] / 3) >= 60 else "Fail", 
    axis=1
)

# 3. Column-wise apply (axis=0): Standardize scores across the subjects
# Axis=0 (default) passes each numerical column as a Series to the lambda function
numerical_cols = ["Math", "Science", "English"]
normalized_df = df[numerical_cols].apply(
    lambda col: (col - col.min()) / (col.max() - col.min()), 
    axis=0
)

print("--- DataFrame with Row-Wise Derived Features ---")
print(df)

print("\n--- Column-Wise Scaled Scores (Min-Max: 0 to 1) ---")
print(normalized_df)

--- DataFrame with Row-Wise Derived Features ---
   Student  Math  Science  English  Total_Score Status
0    Alice    85       90       78          253   Pass
1      Bob    45       55       62          162   Fail
2  Charlie    92       88       95          275   Pass
3    David    60       70       65          195   Pass

--- Column-Wise Scaled Scores (Min-Max: 0 to 1) ---
       Math   Science   English
0  0.851064  1.000000  0.484848
1  0.000000  0.000000  0.000000
2  1.000000  0.942857  1.000000
3  0.319149  0.428571  0.090909
